language: ruby
rvm:
- 2.0.0
branches:
  only:
  - master
script: rake travis
env:
  global:
    secure: id5R7RTEy3oAEOfmjyBu7PWEbHm9M02OvElyQMlNRc2eLGJLgl6hs/Rjuq3ABLrZ+F82x9U4cUJdz9giwtQPZ6uaRw1PFONRhQ493Dz80g+hBt1nHVbTVcCj/seiyiD/yqiLU1arYMvr4GWBNPHcGt06XvdkwiQ11nYgdk0WEb8=
