language: ruby
branches:
  only:
  - master
script: rake travis
env:
  global:
    secure: "AAAAB3NzaC1yc2EAAAADAQABAAACAQDE1PH04S9emq7EveGUBsquUDArpKLIB2V+HyvZ3Yu5/E7jl2sLMpe+VJJo5Pk1YBX2+ink+1DNvAeZ0juC6otHuY+RzCVskT2f6x/HwYfASMTi/bBJLSvH2wcp9QSiqca0vY17ihWryzbCJq6IWQ4z5EuRcCiUXAebRog9/Wx9DFQzDHCh0jzdzZp2UfAt1BbSx54oGFQQdCT4zooytfX/4SMf5fSDlXLJ+1vp5IMx1VwEUENP/7Q3oBt1IJcoxwavlAiCBIhengTPGmGYFH8hDJ5nuv9xV2aNyl2/2KXcZLos4EnH9iNC04rFH82GZjTlXMTReJ4ihUY+103hCM3An2sUZDq0AOxp61CISa8GqTMD1Ktka7aMAvYMRZ3qo/5dXaTsXBWgUm7++1Tpy/pzEkZ3RMtl6U5XEIPkL3ePSaTO0lqSW0bPuXg0zxOikHiEiaScG8PRnJggv75yWlmv1JDiyi1qLIsIPI+gNSkI+/DaYZdwsQgdohGtRiO7T/YpK7qM9vEOv0T8GqDLnqk3SrAQ4EFb4Kc0z/mw924boMMVBpo+BM9gESU2p3IPfLmTmp9fHpIaUl//igVrUmO2bqSlT+W3I943DgeehnAtzfM7cvtbIbIhQz/fiqo3iSkg5leJDdDwKkNZbapBQ6Qvgw6eNYuagFjoAyI0CO0oQw=="

