name: Project Name
title: Baked with Awestruct
org: Organization
base_url: ''

asciidoctor:
  :backend: html5
  :safe: 1
  :attributes:
    imagesdir: ''
    stylesdir: stylesheets

profiles:
  production:
    base_url: http://pepijnve.github.io/geopackage
    deploy:
      host: github_pages
      branch: gh-pages