name: Project Name
title: Baked with Awestruct
org: Organization
base_url: ''

profiles:
  production:
    base_url: http://pepijnve.github.io/geopackage
    deploy:
      host: github_pages
      branch: gh-pages